### ISSUE TITLE
Issue with pin level/transition as a wake-up source

### ISSUE THREAD

**Issue by i-g-g-y** [rocketscream/RocketScream_LowPowerAVRZero#1]
Hello.

I seem to have stumbled on an issue.

If I use this code, the device never wakes-up:
`
#define WAKE 10

attachInterrupt(WAKE, wakeUp, HIGH);
LowPower.powerDown();
`

If I change to 'RISING', it works: 
`
#define WAKE 10

attachInterrupt(WAKE, wakeUp, RISING);
LowPower.powerDown();
`

**Comment by rocketscream** [comment]
This should work on pins Px2 and Px6 of each port. Pin D10 is PC2 which is a valid asynchronous pin that works all the way down to the power down mode.
Have you set the pin into input pin and properly drive the pin from externally or at least having a pull-up?

**Comment by i-g-g-y** [comment]
I am using megaCoreX on a 32-pin Atmega4808. The pin in question is PC2, mcu pin 8, which according to megaCoreX documentation, is Arduino pin 10.

The pin is being driven by a push-pull output, the pin is an input, no pull-up due to power-down current consumption..

**Comment by rocketscream** [comment]
If you look at the datasheet especailly the PINCTRL register, you cannot detect a HIGH but can do the following:

- BOTHEDGES
- RISING
- FALLING
- LEVEL (only on low level)

**Comment by i-g-g-y** [comment]
Yes, I was opened the *.ino from examples directory and it did not work. But apparently the "HIGH" option is not possible for whole avr-0 family.
